export const tagList = [
  {
    tag_id: '0',
    tag_name: '热门',
    des: 'Hi音乐精选热门歌单，涵盖多种风格，总有一款适合你。'
  },
  { tag_id: '587', tag_name: '学习', des: '沉浸式学习BGM，专注提升效率不犯困' },
  {
    tag_id: '660',
    tag_name: '工作',
    des: '打工人专属工作歌单，解压又提效'
  },
  { tag_id: '1104', tag_name: '通勤', des: '通勤路上的治愈旋律，告别拥挤烦恼' },
  {
    tag_id: '69',
    tag_name: '运动',
    des: '燃脂运动必备BGM，节奏拉满超带感'
  },
  { tag_id: '67', tag_name: '校园', des: '重温校园时光，青春氛围感拉满的歌单' },
  { tag_id: '585', tag_name: '旅途', des: '奔赴山海的旅途，有音乐一路相伴' },
  { tag_id: '61', tag_name: '咖啡厅', des: '咖啡厅慵懒氛围，治愈系音乐合集' },
  { tag_id: '581', tag_name: '店铺', des: '提升店铺氛围的宝藏背景音乐' },
  { tag_id: '668', tag_name: '清晨', des: '清晨唤醒耳朵，开启元气满满的一天' },
  {
    tag_id: '670',
    tag_name: '下午茶',
    des: '下午茶时光，慵懒旋律治愈所有疲惫'
  },
  { tag_id: '1105', tag_name: '夜晚', des: '深夜治愈旋律，温柔抚平一天的疲惫' },
  { tag_id: '583', tag_name: '睡前', des: '助眠轻音乐，伴你一夜好眠' },
  { tag_id: '586', tag_name: '派对', des: '派对嗨歌合集，点燃全场欢乐氛围' },
  { tag_id: '1106', tag_name: '宅家', des: '宅家放松必备，慵懒旋律超治愈' },
  { tag_id: '63', tag_name: '车载', des: '车载动感旋律，开车听歌不无聊' },
  { tag_id: '64', tag_name: '夜店', des: '夜店炸场神曲，沉浸式蹦迪体验' },
  { tag_id: '88', tag_name: '婚礼', des: '浪漫婚礼BGM，见证幸福瞬间' },
  { tag_id: '678', tag_name: '瑜伽', des: '瑜伽冥想轻音乐，舒缓身心超放松' },
  { tag_id: '664', tag_name: '做家务', des: '做家务专属BGM，干活不累超解压' },
  {
    tag_id: '580',
    tag_name: '公共交通',
    des: '公交地铁通勤歌单，打发无聊时光'
  },
  { tag_id: '11219', tag_name: '茶馆', des: '茶馆禅意轻音乐，静心品茗超惬意' },
  { tag_id: '11296', tag_name: '露营', des: '露营氛围感音乐，与自然温柔相拥' },
  { tag_id: '1084', tag_name: '精选', des: '精挑细选好歌，每一首都值得循环' },
  { tag_id: '12', tag_name: '经典', des: '岁月沉淀的经典，百听不厌' },
  { tag_id: '35', tag_name: '网络', des: '全网爆火的热门歌曲，不踩雷' },
  { tag_id: '74', tag_name: '游戏', des: '游戏开黑专属BGM，燃爆全场' },
  { tag_id: '17', tag_name: 'DJ热碟', des: '超燃DJ热曲，节奏控的快乐源泉' },
  { tag_id: '68', tag_name: '情歌对唱', des: '甜蜜情歌对唱，甜度超标超好听' },
  { tag_id: '10', tag_name: '舞曲', des: '动感舞曲合集，忍不住跟着摇摆' },
  { tag_id: '72', tag_name: 'KTV', des: 'KTV必点金曲，开口就是全场焦点' },
  { tag_id: '79', tag_name: '影视', des: '热门影视OST，一秒代入剧情' },
  { tag_id: '638', tag_name: '翻唱', des: '神仙翻唱版本，不输原唱更有味道' },
  { tag_id: '77', tag_name: 'ACG', des: '二次元ACG音乐，动漫迷的专属' },
  { tag_id: '680', tag_name: '现场', des: '沉浸式现场版，感受舞台的魅力' },
  { tag_id: '80', tag_name: '综艺', des: '热门综艺BGM，跟着节目嗨起来' },
  { tag_id: '1111', tag_name: '厂牌音乐', des: '小众厂牌宝藏音乐，品味不撞款' },
  { tag_id: '1112', tag_name: 'BGM', des: '万能氛围感BGM，适配所有场景' },
  { tag_id: '1110', tag_name: '儿童', des: '童趣满满儿童歌曲，陪伴快乐成长' },
  {
    tag_id: '682',
    tag_name: '器乐演奏',
    des: '纯器乐演奏，享受音乐的纯粹美好'
  },
  { tag_id: '1085', tag_name: '官方歌单', des: '官方精选歌单，品质有保障' },
  { tag_id: '605', tag_name: '草原风', des: '辽阔草原风歌曲，感受自由与豪迈' },
  { tag_id: '628', tag_name: '广场舞', des: '广场舞热门神曲，节奏踩点超带劲' },
  { tag_id: '84', tag_name: '国语', des: '经典国语歌曲，字字句句都是情怀' },
  { tag_id: '20', tag_name: '英语', des: '超好听的英文歌曲，旋律控的最爱' },
  { tag_id: '19', tag_name: '粤语', des: '经典粤语金曲，港风氛围感拉满' },
  { tag_id: '21', tag_name: '日语', des: '治愈系日语歌曲，温柔又好听' },
  { tag_id: '23', tag_name: '韩语', des: '韩流热门歌曲，旋律上头超洗脑' },
  { tag_id: '22', tag_name: '闽南语', des: '闽南语经典老歌，满满家乡味' },
  { tag_id: '24', tag_name: '小语种', des: '小众好听的小语种歌曲，品味独特' },
  { tag_id: '570', tag_name: '法语', des: '浪漫法语歌曲，感受法式温柔' },
  { tag_id: '9', tag_name: '流行', des: '全网热播流行歌曲，紧跟音乐潮流' },
  { tag_id: '574', tag_name: '古风', des: '唯美古风歌曲，一秒穿越千年' },
  { tag_id: '33', tag_name: '电子', des: '炸裂电子音乐，节奏控的狂欢' },
  { tag_id: '83', tag_name: '民谣', des: '治愈系民谣，温柔抚平所有烦恼' },
  { tag_id: '27', tag_name: '摇滚', des: '热血摇滚歌曲，释放内心的热爱' },
  { tag_id: '31', tag_name: '说唱', des: '硬核说唱合集，flow超顶超带感' },
  { tag_id: '1079', tag_name: '后摇', des: '氛围感后摇，沉浸式音乐体验' },
  { tag_id: '11', tag_name: '中国风', des: '国潮中国风，韵味十足超好听' },
  { tag_id: '30', tag_name: 'R&B', des: '慵懒R&B旋律，放松身心超治愈' },
  { tag_id: '28', tag_name: '古典', des: '经典古典音乐，提升审美与气质' },
  { tag_id: '15', tag_name: '乡村', des: '清新乡村音乐，感受自然与自由' },
  { tag_id: '32', tag_name: '爵士', des: '慵懒爵士旋律，氛围感拉满' },
  { tag_id: '650', tag_name: '新世纪', des: '新世纪轻音乐，舒缓身心超放松' },
  { tag_id: '94', tag_name: '布鲁斯', des: '经典布鲁斯，品味复古音乐魅力' },
  { tag_id: '1057', tag_name: '拉丁', des: '热情拉丁音乐，忍不住跟着摇摆' },
  { tag_id: '34', tag_name: '轻音乐', des: '治愈轻音乐，抚平所有焦虑与疲惫' },
  { tag_id: '1108', tag_name: '中国传统', des: '传统民乐，感受东方音乐之美' },
  { tag_id: '29', tag_name: '金属', des: '硬核金属乐，释放内心的狂野' },
  { tag_id: '92', tag_name: '雷鬼', des: '随性雷鬼节奏，轻松又自在' },
  { tag_id: '1078', tag_name: '另类独立', des: '小众另类独立音乐，品味不撞款' },
  { tag_id: '1107', tag_name: '怀旧', des: '怀旧金曲，重温那些年的美好时光' },
  { tag_id: '578', tag_name: '伤感', des: '治愈伤感歌曲，抚平内心的难过' },
  { tag_id: '44', tag_name: '安静', des: '安静治愈旋律，与自己温柔相处' },
  { tag_id: '50', tag_name: '兴奋', des: '超燃兴奋神曲，点燃所有快乐' },
  { tag_id: '577', tag_name: '轻松', des: '轻松治愈旋律，卸下所有疲惫' },
  { tag_id: '780', tag_name: '治愈', des: '治愈系歌曲，温柔抚平所有伤痛' },
  { tag_id: '49', tag_name: '快乐', des: '超甜快乐歌曲，治愈所有不开心' },
  { tag_id: '47', tag_name: '甜蜜', des: '甜蜜情歌合集，甜度超标超心动' },
  { tag_id: '42', tag_name: '寂寞', des: '治愈寂寞的旋律，与自己和解' },
  { tag_id: '48', tag_name: '感动', des: '催泪感动歌曲，治愈内心的柔软' },
  { tag_id: '642', tag_name: '小清新', des: '小清新治愈旋律，元气满满超可爱' },
  { tag_id: '81', tag_name: '励志', des: '励志正能量歌曲，给你无限动力' },
  { tag_id: '643', tag_name: '减压', des: '减压治愈旋律，释放所有压力' },
  { tag_id: '684', tag_name: '失恋', des: '治愈失恋的歌，陪你走过低谷期' },
  { tag_id: '13', tag_name: '70后', des: '70后的青春记忆，经典老歌合集' },
  { tag_id: '14', tag_name: '80后', des: '80后的专属回忆，每首都是经典' },
  { tag_id: '76', tag_name: '90后', des: '90后的青春歌单，满满回忆杀' },
  { tag_id: '571', tag_name: '00后', des: '00后超爱的热门歌曲，潮流不落后' }
]
